spring:
  application:
    name: email
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_email_ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://seal.lmq.cloudamqp.com
    username: nljzopxg
    password: 9C3iItHh4OQ1MLyuOeEpDPHxQu9Ipp-l
    virtual-host: nljzopxg

server:
  port: 8080